import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/custom/theme-provider";
import {SettingsProvider} from "@/app/settings/SettingsContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SettingsProvider>
                {children}
            </SettingsProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
